### ISSUE TITLE
mpi4py installation error -Remediation

### ISSUE THREAD

**Issue by Phoenix9032** [microsoft/msrflute#10]
![image](https://user-images.githubusercontent.com/30574946/174451768-97b91b0a-987d-43a9-871e-9d16e8abef00.png)

Hello - If you find the build error for mpi4py installation you need to install 
```
apt-get install libopenmpi-dev -y

```
This should solve the issue

**Comment by Mirian-Hipolito** [comment]
Hi @Phoenix9032, thanks for letting us know. We will make sure to include these instructions in the readme for the next PR.
