### ISSUE TITLE
Annealing LR Scheduler required?

### ISSUE THREAD

**Issue by hackenjoe** [microsoft/msrflute#19]
Is it possible to disable the annealing LR scheduler? If it is removed from the `config.yaml` file, the training process will not start.

**Comment by amanoel** [comment]
Hi @hackenjoe! Indeed we do enforce the need of a scheduler, we should relax this. For the moment what you can do is using a `step_lr` scheduler with `gamma = 1.0`, that way the learning rate will stay always the same. This is already done in some of the config examples we provide.
