### ISSUE TITLE
Request fo Xbox client

### ISSUE THREAD

**Issue by citron** [microsoft/msrflute#8]
Hello
This is a suggestion, not a bug report. 
May we expect to see an Xbox client ?
I am ready to help.

**Comment by simra** [comment]
Hi @citron thanks for your interest in FLUTE.  The platform is a simulator best suited for running batch simulations on multi-GPU devices. It could run on XBox if you can get a suitable python environment set up (including pytorch).  Happy to discuss more if you think this an interesting direction.
