### ISSUE TITLE
The git submodule of Privacy Accounting didnt work

### ISSUE THREAD

**Issue by Phoenix9032** [microsoft/msrflute#9]
$ git submodule update --init --recursive
I could not get this to work at all . Finally  I had to go through commit logs to find out the prv_accountant repository
https://github.com/microsoft/prv_accountant 

I cloned it , set the path variable for prv_accountant module after setup.py and it worked .

**Comment by Mirian-Hipolito** [comment]
Hi @Phoenix9032 , we have updated the submodule pointers in the latest commit, it should work now.  Please feel free to open again this issue in case you're still having issues with the submodule.
